export const BUILTIN_SHOWCASE_CHANNELS = [
  { name: "France 24 Français (Live News)", logo: "https://static.france24.com/assets/f24_logo.png", category: "News / Actualités", url: "https://static.france24.com/live/F24_FR_LO_HLS/live_tv.m3u8" },
  { name: "France 24 English (Live News)", logo: "https://static.france24.com/assets/f24_logo.png", category: "News / Actualités", url: "https://static.france24.com/live/F24_EN_LO_HLS/live_tv.m3u8" },
  { name: "NASA TV Global (Science & Space)", logo: "https://www.nasa.gov/wp-content/themes/nasa/assets/images/nasa-logo.svg", category: "Documentary & Space", url: "https://ntv1.nasatv.live/nasatv/nasa_direct_rtmp/playlist.m3u8" },
  { name: "Red Bull TV Live (Sports & Action)", logo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f5/Red_Bull_Energy_Drink_logo.svg/220px-Red_Bull_Energy_Drink_logo.svg.png", category: "Sports / Action", url: "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8" },
  { name: "Bloomberg Global Wealth & Finance", logo: "https://upload.wikimedia.org/wikipedia/commons/5/54/Bloomberg_logo.svg", category: "News & Business", url: "https://liveproduction.choiceclip.com/bloomberg/bloomberg_live.m3u8" },
  { name: "Deutsche Welle TV (Live HD)", logo: "https://upload.wikimedia.org/wikipedia/commons/5/5b/Deutsche_Welle_logo_2012.svg", category: "News / Actualités", url: "https://dwstream4-lh.akamaihd.net/i/dwstream4_live@131313/master.m3u8" },
  { name: "Fashion TV Global Fashion Channel", logo: "https://upload.wikimedia.org/wikipedia/commons/e/ea/LogoFTV.png", category: "Entertainment & Life", url: "https://fash1043.cloudycdn.services/slive/_definst_/ftv_ftv_mid_alt_hd_3500/playlist.m3u8" },
  { name: "CGTN Français (Actualités & Culture)", logo: "https://upload.wikimedia.org/wikipedia/commons/7/7a/CGTN_logo.svg", category: "News & Culture", url: "https://livecgtnf.cgtn.com/1000f/prog_index.m3u8" }
];

export const ADULT_PRESET_CHANNELS = [
  { name: "Playboy (+18) | HD", logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREBiSUXjULWkg9ugs9mSztJg9uuUd3g9QCgHjl1ttF2kgi9CollR2tN6aXMczPlMl_0To&usqp=CAU", category: "Adult / +18", url: "https://edge3.prepro.cvattv.com.ar/live/vod/Playboy/SA_Live_WebVTT_FTA/Playboy.m3u8" },
  { name: "VENUS - USA (+18) | HD", logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Old_Canal_Venus_logo.svg/2560px-Old_Canal_Venus_logo.svg.png", category: "Adult / +18", url: "https://edge4-sl.cvattv.com.ar/live/c6eds/Venus/SA_SAGEMCOM/Venus.m3u8" },
  { name: "A3BIKINI - USA (+18) | HD", logo: "https://i.postimg.cc/NGKPwybC/A3-BIKINI-MODIFICADA.png", category: "Adult / +18", url: "https://vcnbikininetwork.teleosmedia.com/stream/bikininetwork/a3bikini/seglist_720p.m3u8" },
  { name: "FASHION TV MIDNIGHT SECRETS - USA (+18) | HD", logo: "https://i.postimg.cc/NGKPwybC/A3-BIKINI-MODIFICADA.png", category: "Adult / +18", url: "https://fash1043.cloudycdn.services/slive/ftv_midnite_secrets_adaptive.smil/chunklist_b1300000_t64MzYwcA==.m3u8" },
  { name: "FASHION TV - USA (+18) | HD", logo: "https://i.postimg.cc/NGKPwybC/A3-BIKINI-MODIFICADA.png", category: "Adult / +18", url: "https://fash1043.cloudycdn.services/slive/ftv_ftv_midnite_k1y_27049_midnite_secr_108_hls.smil/playlist.m3u8" },
  { name: "MIAMI TV - USA (+18) | HD", logo: "https://vivaespaña.tv/user/live-tv/miamitv-latino/31", category: "Adult / +18", url: "https://59ec5453559f0.streamlock.net/miamitv/smil:WEB/playlist.m3u8" },
  { name: "TV Adultos POV (+18) | HD", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / +18", url: "http://cdn.adultiptv.net/pov.m3u8?PlaylistM3UCL" },
  { name: "TV Adultos Teens (+18) | HD", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / +18", url: "http://cdn.adultiptv.net/teen.m3u8?PlaylistM3UCL" },
  { name: "TV Adultos GangBang (+18) | HD", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / +18", url: "http://cdn.adultiptv.net/gangbang.m3u8?PlaylistM3UCL" },
  { name: "TV Adultos Brunette (+18) | HD", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / +18", url: "http://cdn.adultiptv.net/brunette.m3u8?PlaylistM3UCL" },
  { name: "TV Adultos Blonde (+18) | HD", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / +18", url: "http://cdn.adultiptv.net/blonde.m3u8?PlaylistM3UCL" },
  { name: "TV Adultos Live Cams (+18) | HD", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / +18", url: "http://cdn.adultiptv.net/livecams.m3u8?PlaylistM3UCL" },
  { name: "TV Adultos Latina (+18) | HD", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / +18", url: "http://cdn.adultiptv.net/latina.m3u8?PlaylistM3UCL" },
  { name: "TV Adultos MILF (+18) | HD", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / +18", url: "http://cdn.adultiptv.net/milf.m3u8?PlaylistM3UCL" },
  { name: "AdultIPTV.net Live Cams", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/livecams.m3u8" },
  { name: "AdultIPTV.net MILF", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/milf.m3u8" },
  { name: "AdultIPTV.net Big Dick", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/bigdick.m3u8" },
  { name: "AdultIPTV.net Big Tits", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/bigtits.m3u8" },
  { name: "AdultIPTV.net Fetish", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/fetish.m3u8" },
  { name: "AdultIPTV.net Pornstar", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/pornstar.m3u8" },
  { name: "AdultIPTV.net Big Ass", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/bigass.m3u8" },
  { name: "AdultIPTV.net Interracial", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/interracial.m3u8" },
  { name: "AdultIPTV.net Latina", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/latina.m3u8" },
  { name: "AdultIPTV.net POV", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/pov.m3u8" },
  { name: "AdultIPTV.net Blowjob", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/blowjob.m3u8" },
  { name: "AdultIPTV.net Teen", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/teen.m3u8" },
  { name: "AdultIPTV.net Hardcore", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/hardcore.m3u8" },
  { name: "AdultIPTV.net Cuckold", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/cuckold.m3u8" },
  { name: "AdultIPTV.net Threesome", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/threesome.m3u8" },
  { name: "AdultIPTV.net Russian", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/russian.m3u8" },
  { name: "AdultIPTV.net Lesbian", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/lesbian.m3u8" },
  { name: "AdultIPTV.net Rough", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/rough.m3u8" },
  { name: "AdultIPTV.net Gangbang", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/gangbang.m3u8" },
  { name: "AdultIPTV.net Anal", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/anal.m3u8" },
  { name: "AdultIPTV.net Compilation", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/compilation.m3u8" },
  { name: "AdultIPTV.net Brunette", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/brunette.m3u8" },
  { name: "AdultIPTV.net Blonde", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/blonde.m3u8" },
  { name: "AdultIPTV.net Gay", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/gay.m3u8" },
  { name: "AdultIPTV.net Asian", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / XXX", url: "http://cdn.adultiptv.net/asian.m3u8" },
  { name: "TV Adultos Pornstars (+18) | HD", logo: "https://files.adultiptv.net/adultiptvnet.jpg", category: "Adult / +18", url: "http://cdn.adultiptv.net/pornstar.m3u8?PlaylistM3UCL" }
];
